### ISSUE TITLE
Calcul de synergie

### ISSUE THREAD

**Issue by JulienChavee** [JulienChavee/bruminator2.0#73]
#0 /var/www/bruminator/default/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(147): Doctrine\ORM\Internal\Hydration\SingleScalarHydrator->hydrateAllData()
#1 /var/www/bruminator/default/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(978): Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll(Object(Doctrine\DBAL\Driver\PDOStatement), Object(Doctrine\ORM\Query\ResultSetMapping), Array)
#2 /var/www/bruminator/default/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(924): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 4)
#3 /var/www/bruminator/default/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(804): Doctrine\ORM\AbstractQuery->execute(NULL, 4)
#4 /var/www/bruminator/default/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(833): Doctrine\ORM\AbstractQuery->getSingleResult(4)
#5 /var/www/bruminator/default/src/TeamBundle/Repository/SynergieClassRepository.php(32): Doctrine\ORM\AbstractQuery->getSingleScalarResult()
#6 /var/www/bruminator/default/src/TeamBundle/Repository/SynergieClassRepository.php(87): TeamBundle\Repository\SynergieClassRepository->getSynergie(11, '16')
#7 /var/www/bruminator/default/src/TeamBundle/Controller/TeamController.php(334): TeamBundle\Repository\SynergieClassRepository->getClass4('17', '7', '16')
#8 [internal function]: TeamBundle\Controller\TeamController->frontSynergieAjaxGetClass4(Object(Symfony\Component\HttpFoundation\Request))
#9 /var/www/bruminator/default/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(153): call_user_func_array(Array, Array)
#10 /var/www/bruminator/default/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#11 /var/www/bruminator/default/var/bootstrap.php.cache(1447): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/www/bruminator/default/web/app.php(18): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}

**Comment by JulienChavee** [comment]
Se produit car il y a 2 synergie pour deux mêmes classes.
Il faudrait vérifier que l'édition d'une synergie ne créé pas une nouvelle ...

**Comment by JulienChavee** [comment]
> Se produit car il y a 2 synergie pour deux mêmes classes.
>Il faudrait vérifier que l'édition d'une synergie ne créé pas une nouvelle ...

Après test, l'édition de synergie fonctionne correctement. Je ne sais pas d'où provient ce problème. A surveiller dans le futur
